### ISSUE TITLE
Classes for DOM elements

### ISSUE THREAD

**Issue by suhr** [evanshort73/chords#15]
I wanted to improve the UI with a userstyle, but DOM elements lack classes.

**Comment by evanshort73** [comment]
Interesting. Adding classes is easy. Can you give me some guidance on which elements need classes, and which groups of elements should have the same class?

**Comment by suhr** [comment]
> which elements need classes

More is better.

> which groups of elements should have the same class

Well, it's useful to have different classes for different things and same classes for same things.

**Comment by evanshort73** [comment]
Sorry, but it's not at all obvious to me how to assign classes. If you can list some specific types of things you want to style, I'll be happy to add classes for them.

**Comment by suhr** [comment]
At least everything with `grid-area`. Though their elements also need classes.

Actually, you already have some names in your code (`viewBpm`, `viewScale`, etc...). Why not make corresponding classes for these names?

**Comment by evanshort73** [comment]
Sure, I'll start with assigning an id to the parent element of each grid area. I could also add classes for checkbox, range input, chord button, chord button blue border, and chord button dashed blue border.

**Comment by evanshort73** [comment]
Ok, these changes should be live now (may have to hard refresh).
